namespace InteractiveBrokers.Enums
{
  public enum PropertyEnum : int
  {
    BidSize = 0,
    BidPrice = 1,
    AskPrice = 2,
    AskSize = 3,
    LastPrice = 4,
    LastSize = 5,
    High = 6,
    Low = 7,
    Volume = 8,
    ClosePrice = 9,
    BidOptionComputation = 10,
    AskOptionComputation = 11,
    LastOptionComputation = 12,
    ModelOptionComputation = 13,
    OpenPrice = 14,
    Low13Week = 15,
    High13Week = 16,
    Low26Week = 17,
    High26Week = 18,
    Low52Week = 19,
    High52Week = 20,
    AverageVolume = 21,
    OpenInterest = 22,
    OptionHistoricalVolatility = 23,
    OptionImpliedVolatility = 24,
    OptionCallOpenInterest = 27,
    OptionPutOpenInterest = 28,
    OptionCallVolume = 29,
    OptionPutVolume = 30,
    IndexFuturePremium = 31,
    BidExchange = 32,
    AskExchange = 33,
    AuctionVolume = 34,
    AuctionPrice = 35,
    AuctionImbalance = 36,
    MarkPrice = 37,
    BidEfpComputation = 38,
    AskEfpComputation = 39,
    LastEfpComputation = 40,
    OpenEfpComputation = 41,
    HighEfpComputation = 42,
    LowEfpComputation = 43,
    CreditmanMarkPrice = 46,
    CreditmanSlowMarkPrice = 47,
    ShortableShares = 48,
    FundamentalRatios = 49,
    RtVolume = 50,
    Halted = 51,
    BidYield = 52,
    AskYield = 53,
    LastYield = 54,
    CustOptionComputation = 55,
    TradeCount = 56,
    TradeRate = 57,
    VolumeRate = 58,
    LastRthTrade = 59
  }
}
